name: Simple CI job

on:
  push:
    branches: [ "main", "hmw5" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print message to console
        run: |
          echo "Current date and time: $(date)"
