name: date CI
on:
  push:
    branches: ["Ulyalike-patch-4"]
  pull_request:
    branches: ["Ulyalike-patch-4"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print date
        run: date +"%Y-%m-%d %T"
